### ISSUE TITLE
"requested transition does not exist" while connecting to OBS

### ISSUE THREAD

**Issue by quiquelhappy** [ThomasK33/vscode-obs-switcher#15]
![](https://i.imgur.com/GFkBv9g.png)

**Comment by quiquelhappy** [comment]
Okay, apparently, OBS locale must be set to english, because the names of the transitions do change from locale to locale, so cut only works with English. I'm unaware about if this could be fixed by using a transition 'number' or other identificator that is not locale dependant.

**Comment by ThomasK33** [comment]
Hello there.

Unfortunately the transition name requirement is set by the obs-websocket plugin, see: https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#switchtransition

To workaround this locale dependency, one can now set the transition name in the settings of this extension. 
The option is called `transition` and defaults to `"Cut"`. It can be set to the corresponding name in the language your OBS is in.
