### ISSUE TITLE
cannot connect to obs in linux

### ISSUE THREAD

**Issue by scarf005** [ThomasK33/vscode-obs-switcher#256]
## System info
```
Kernel: 5.15.0-46-generic
OBS Studio - 27.2.4 (linux)
code: 1.70.2, e4503b30fc78200f846c62cf8091b76ff5547662, x64
version: 0.1.2
```
- clicking `Connect to OBS` button does nothing. 
- `obs switcher: Connect to OBS` does nothing.
- no log, no error popups (it did pop up, but gone after i've set up connection password), no everything.
- can connect to websocket via `wscat -c "ws://localhost:4455"`, so obs websocket is working.
![_02](https://user-images.githubusercontent.com/54838975/185276740-2bd34ff0-3168-484e-aca1-8b914244b3fc.png)

**Comment by Sandros94** [comment]
same in windows with the built in websocket of OBS v28 (wscat works fine)

**Comment by quiquelhappy** [comment]
Seems like this extension is broken on OBS v28<=

**Comment by quiquelhappy** [comment]
obs-websocket shows the following output:
```
13:08:23.969: [obs-websocket] [WebSocketServer::onMessage] Client [::ffff:127.0.0.1]:57172 appears to be running a pre-5.0.0 protocol.
13:08:23.969: [obs-websocket] [WebSocketServer::onClose] WebSocket client `[::ffff:127.0.0.1]:57172` has disconnected with code `4010` and reason: You appear to be attempting to connect with the pre-5.0.0 plugin protocol. Check to make sure your client is updated.
```

**Comment by quiquelhappy** [comment]
https://github.com/ThomasK33/vscode-obs-switcher/pull/265
