### ISSUE TITLE
How to set credentials on windows

### ISSUE THREAD

**Issue by opti21** [ThomasK33/vscode-obs-switcher#64]
Not exactly sure how to set the credentials on windows

I tried using the credential manager but it requires a username does the websocket connection require one?

**Comment by ThomasK33** [comment]
Hey,

if you enable authentication and set a password inside of the WebSocket server settings extension in OBS, you'll have to pass the password along for this extension to use.

![image](https://user-images.githubusercontent.com/2198487/111066402-1c19b980-84bf-11eb-889f-8dbf699e8132.png)

The password can be set using the command "OBS Switcher: Set OBS password" (found in the Command Palette)

![image](https://user-images.githubusercontent.com/2198487/111066440-5a16dd80-84bf-11eb-9c6e-f7416cf8c54a.png)

Which then will present a prompt for the password
![image](https://user-images.githubusercontent.com/2198487/111066453-73b82500-84bf-11eb-8864-3e8c1bc3a1eb.png)

**Comment by opti21** [comment]
Oh awesome thank you :)
